### PR TITLE
Fix when no schema selected

### LINKED ISSUE #52: Outil cassé ?
La page [csv-gg.etalab.studio](https://csv-gg.etalab.studio/) n'affiche plus que le header et le footer de l'application.

### PR DESCRIPTION
**Pull request by abulte**
Fix #52

### CODE REVIEW

File: src/views/Home.vue [hunk 1]
```diff
@@ -22,7 +22,7 @@
                 </template>
             </b-form-select>
         </b-form-group>
-        <b-alert v-if="schema.name === 'etalab/schema-lieux-covoiturage'" show dismissible>
+        <b-alert v-if="schema && schema.name === 'etalab/schema-lieux-covoiturage'" show dismissible>
```
Comment (geoffreyaldebert) [inline src/views/Home.vue:25]: Sorry for that ...
Good for me !
